* Quickmsg

Quickmsg is meant to be a thin application utility layer on top of Zyre/ZeroMQ and MessagePack, supporting simple group messaging. The primary message type (for now) is a JSON string, transformed to a compact binary format using MessagePack before transmission to a Zyre group. The API is being initially developed in C++, and is intended to be wrapped using a tool such as SWIG for use by multiple target languages. 

The following components have initial implementations:

- *Publisher*: publishes messages to a topic
- *Subscriber*: receives messages from a topic (can be used synchronously and asynchronously / with a callback)
- *Service*: provide an RPC-like service interface for...
- *Client*: issues requests to a Service and blocks for a reply
- *GroupNode*: low-level implementation allowing alternative patterns and supporting a promiscuous message handling mode.

** Dependencies
- Sodium, from source or pkg-manager (libsodium-dev)
- [[https://github.com/open-source-parsers/jsoncpp][Jsoncpp]], from source or pkg-manager (libjsoncpp-dev)
- [[https://github.com/google/glog.git][Google logging]], from source or pkg-manager (libgoogle-glog-dev)
- [[http://www.swig.org/][Swig 3.0]], from source or pkg-manager (swig)
- Python 2.7, from source or pkg-manager (python-dev)
- TBB (Intel Threading Building Blocks), from source or pkg-manager (libtbb-dev)
- Boost libraries, from source or pkg-manager (libboost-all-dev)
- ZeroMQ stack: [[https://github.com/zeromq/libzmq][libzmq]], [[https://github.com/zeromq/czmq][czmq]], and [[https://github.com/zeromq/zyre][zyre]], *from source* using cmake
  - libzmq: git clone https://github.com/zeromq/libzmq.git -b v4.2.2
  - czmq: git clone https://github.com/zeromq/czmq.git -b v4.1.0
  - zyre: git clone https://github.com/zeromq/zyre -b v2.0.0

** SWIG Wrapping

SWIG is a tool to generate wrappers for C/C++ code to a variety of high-level langauges, including Python, Java and Common Lisp. 

Although there are [[http://www.swig.org/Doc3.0/Allegrocl.html][pages]] indicating SWIG support for Common Lisp, there is contrary [[https://github.com/swig/swig/issues/384#issuecomment-100715041][evidence]] that in fact Common Lisp support is not active or maintained.

Therefore, we do not use SWIG to generate the Common Lisp bindings, but instead implement a simple C wrapper that can be called directly with [[https://common-lisp.net/project/cffi/][CFFI]].

See the [[test]] directory for simple language tests and usage examples for C, C++, Java, Python, and Common Lisp. 

The Common Lisp examples were tested with sbcl. The required common lisp packages, such as [[https://common-lisp.net/project/cl-json/][cl-json]], were installed using [[https://www.quicklisp.org/beta/][quicklisp]]
