################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

# for the version we are using...
set(LIBNAME1 "czmq")
set(LIBNAME2 "libczmq")

if (NOT MSVC)
  include(FindPkgConfig)
  pkg_check_modules(PC_CZMQ ${LIBNAME1})
  if (NOT PC_CZMQ_FOUND)
    pkg_check_modules(PC_CZMQ ${LIBNAME2})
    if (PC_CZMQ_FOUND) 
      set(LIBNAME ${LIBNAME2})
    endif()
  else()
    set(LIBNAME ${LIBNAME1})
  endif (NOT PC_CZMQ_FOUND)
  if (PC_CZMQ_FOUND)
    # some libraries install the headers is a subdirectory of the include dir
    # returned by pkg-config, so use a wildcard match to improve chances of finding
    # headers and SOs.
    set(PC_CZMQ_INCLUDE_HINTS ${PC_CZMQ_INCLUDE_DIRS} ${PC_CZMQ_INCLUDE_DIRS}/*)
    set(PC_CZMQ_LIBRARY_HINTS ${PC_CZMQ_LIBRARY_DIRS} ${PC_CZMQ_LIBRARY_DIRS}/*)
  endif(PC_CZMQ_FOUND)
endif (NOT MSVC)

message("Search for CZMQ include dirs")
find_path (
  CZMQ_INCLUDE_DIRS
  NAMES czmq.h
  HINTS ${PC_CZMQ_INCLUDE_HINTS}
  )

message("Search for CZMQ library dirs")
find_library (
  CZMQ_LIBRARIES
  NAMES ${LIBNAME1} ${LIBNAME2}
  HINTS ${PC_CZMQ_LIBRARY_HINTS}
  )

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
  CZMQ
  REQUIRED_VARS CZMQ_LIBRARIES CZMQ_INCLUDE_DIRS
  )
mark_as_advanced(
  CZMQ_FOUND
  CZMQ_LIBRARIES CZMQ_INCLUDE_DIRS
  )

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
